name: monero
description: Dart library for monero
version: 0.0.0
repository: https://git.mrcyjanek.net/mrcyjanek/monero.dart

environment:
  sdk: ^3.0.0

dependencies:
  ffi: ^2.1.0
  ledger_flutter: ^1.0.1

dependency_overrides:
  ledger_usb:
    git:
      url: https://github.com/MrCyjaneK/ledger-usb
      ref: 5da9a55a7ca561c13962eb29e5c45ff8d3726172

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
  ffigen: ^12.0.0
